### ISSUE TITLE
Duplicate query identifier

### ISSUE THREAD

**Issue by sqmatheus** [cooldogepm/libSQL#11]
Hello, first of all awesome lib :)

```php
class InsertPetStatsQuery extends SQLiteQuery
{
  public function __construct(
    protected string $xuid,
    ...
  ) {
  }
}
```
```php
public function savePetStats(string $xuid, ....): void {
    $query = new InsertPetStatsQuery($xuid, ...);
    $this->connectionPool->submit($query);
}
```
I ran this code:
```php
$this->savePetStats($xuid, ...);
$this->savePetStats($xuid, ...);
$this->savePetStats($xuid, ...);
```

And I got this error:

```
[14:08:51.339] [Server thread/CRITICAL]: ErrorException: "Undefined array key 137211" (EXCEPTION) in "plugins/Pets.phar/src/pets/libs/_0fcaf78ab8e7f99c/cooldogedev/libSQL/ConnectionPool" at line 84
```

I started investigating by putting `var_dump($query->getIdentifier());` after submitting the query and got this:

```
int(137211)
int(137210)
int(137211)
```

I don't know if I'm doing something wrong, but I think the problem is using `spl_object_id` as the query identifier.

**Comment by cooldogedev** [comment]
Thanks and I fixed it in https://github.com/cooldogepm/libSQL/commit/f187c02c27b109af2750eb98433f716d804023e1

**Comment by cooldogedev** [comment]
On an unrelated note, you should use the queries' execution method `$query->execute(onSuccess, onError)` instead of using the `ConnectionPool` directly

**Comment by sqmatheus** [comment]
I didn't know that, thanks!
