### ISSUE TITLE
Making Many Files for Different Queries

### ISSUE THREAD

**Issue by oPinqzz** [cooldogepm/libSQL#14]
Hi I use this for my server and noticed That When I Need to Enter Data i need to make new file 
Example :
I created a Query For Ranks Data
if i want to get ranks data i need to create a new class 
so i made this solution 
https://github.com/iAbdo2008/DatabaseManager
which fixes that by using one query system as execution or fix

**Comment by cooldogedev** [comment]
it isn't a fix, libSQL is designed to be used with ORMs, Query Builders and such.
