### ISSUE TITLE
"Installation" is an inaccurate word

### ISSUE THREAD

**Issue by SOF3** [cooldogepm/libSQL#3]
You can't "install" a virion. A virion is not a plugin. DEVirion is only used for development testing.

**Comment by cooldogedev** [comment]
solved in https://github.com/cooldogedev/libSQL/commit/1aff7a83ae4526c6e1dbfff899ef137806101682

**Comment by SOF3** [comment]
It still says "Instlalation via DEVirion"

**Comment by cooldogedev** [comment]
This should solve it https://github.com/cooldogedev/libSQL/commit/27fc00604bd020e5e8e0727328a66f3679636887
